Catch NoClassDefFoundError too (#57)
Catch NoClassDefFoundError too

Related to #56 we need to catch also NoClassDefFoundError too for when classes were present at compile time but missing at runtime.