Catch ClassDefNotFoundError one more time.
Similar to the previous commit (related to #56) we need to also catch both ClassNotFoundException and NoClassDefFoundError
to avoid problems when we have compile-time dependencies which are not present at runtime.

Related to #56